server.port=8080

# Pinata IPFS Credentials
# Pinata IPFS Configuration
pinata.api.key=${PINATA_API_KEY:}
pinata.api.secret=${PINATA_API_SECRET:}
pinata.jwt=${PINATA_JWT:}
web3.private-key=${WEB3_PRIVATE_KEY:}
web3.contract-address=${WEB3_CONTRACT_ADDRESS:}

spring.datasource.url=jdbc:h2:mem:transplantdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update